export default {
    csk:[{name:"MS Dhoni(c)",
          role:"wk",
          status:false},

          {name:"Devon Conway",
          role:"bt",
          status:false},
          {name:"Ruturaj Gaikead",
          role:"bt",
          status:false},
          {name:"Ambati Raydu",
          role:"bt",
          status:false},
          {name:"Subhranshu",
          role:"bt",
          status:false},

          {name:"Ravindra Jadeja",
          role:"ar",
          status:false},
          {name:"Shivam Dube",
          role:"ar",
          status:false},
          
          {name:"Rajvardhan",
          role:"bw",
          status:false},
          {name:"Tushar",
          role:"bw",
          status:false},
          {name:"Akash",
          role:"bw",
          status:false},
          {name:"Simarjeet",
          role:"bw",
          status:false}
        ],

        mi:[{name:"vishnu vinod",
          role:"wk",
          status:false},

          {name:"Rohit Sharma (c)",
          role:"bt",
          status:false},
          {name:"Sandeep Warrier",
          role:"bt",
          status:false},
          {name:"Ishan Kishan",
          role:"bt",
          status:false},
          {name:"Surya Kumar",
          role:"bt",
          status:false},

          {name:"Tim David",
          role:"ar",
          status:false},
          {name:"Hrithik",
          role:"ar",
          status:false},
          
          {name:"Kumar karthikeya",
          role:"bw",
          status:false},
          {name:"Jason",
          role:"bw",
          status:false},
          {name:"Akash (mi)",
          role:"bw",
          status:false},
          {name:"Arjun",
          role:"bw",
          status:false}
        ],

}
